//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhu.Graywulf.DBSubset.Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jhu.Graywulf.DBSubset.Lib.ScriptTemplates", typeof(ScriptTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⴠ‭湉敳瑲猠扵敳⁴湩潴搠獥楴慮楴湯琠扡敬਍䤠华剅⁔⑛敄瑳湩瑡潩呮扡敬⁝䥗䡔⠠䅔䱂䍏塋ഩ †⠠⑛湉敳瑲潃畬湭楌瑳⥝਍匠䱅䍅⁔⑛敓敬瑣潃畬湭楌瑳൝ 剆䵏†嬠匤畯捲呥扡敬⁝潳牵散慴汢慥楬獡圠呉⁈丨䱏䍏⥋਍嬉匤畯捲呥扡敬潊湩嵳഻ .
        /// </summary>
        internal static string FullTableQuery {
            get {
                return ResourceManager.GetString("FullTableQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⴠ‭牃慥整琠浥潰慲祲琠扡敬映牯琠敨爠湡潤⁭䑉氠獩൴ 䙉䔠䥘呓⡓匠䱅䍅⁔‪剆䵏琠浥摰⹢扤⹯祳潳橢捥獴圠䕈䕒䤠⁄‽䉏䕊呃䥟⡄❎整灭扤⸮⌣整灭牯牡楹汤獩❴⤩਍䐠佒⁐䅔䱂⁅⌣整灭牯牡楹汤獩㭴਍ⴠ䜭൏ഊ 剃䅅䕔吠䉁䕌⌠琣浥潰慲祲摩楬瑳਍⠠਍嬉吤浥呰扡敬潃畬湭嵳਍⤠഻ ਍ⴠ‭潃汬捥⁴䑉൳ 䥗䡔琠浥潰慲祲摩楬瑳畱牥⁹十਍⠠਍匉䱅䍅⁔⑛牐浩牡䭹祥潃畬湭䅳楬獡ⱝ洠獡整⹲扤⹯慒摮浯潄扵敬⤨䄠⁓慲摮浯畮扭牥਍䘉佒⁍⑛潓牵散慔汢嵥猠畯捲瑥扡敬污慩൳ऊ⑛潓牵散慔汢䩥楯獮൝ ഩ 义䕓呒⌠琣浥潰慲祲摩楬瑳圠呉⁈吨䉁佌䭃⥘਍匠䱅䍅⁔⑛牐浩牡䭹祥潃畬湭嵳਍䘠佒⁍整灭牯牡楹汤獩煴敵祲਍圠䕈䕒爠湡潤湭浵敢⁲‼⑛慓灭楬杮慆瑣牯㭝਍ഠ ⴭ䤠獮牥⁴畳獢瑥椠瑮⁯敤瑳湩瑡潩⁮慴汢൥ ਍䤠华剅⁔⑛敄瑳湩瑡潩呮扡敬⁝䥗䡔⠠䅔䱂䍏塋ഩऊ嬨䤤獮牥䍴汯浵䱮獩嵴ഩ 䕓䕌呃嬠匤汥捥䍴汯浵䱮獩嵴਍䘠佒⁍†⑛潓牵散慔汢嵥猠畯捲瑥扡敬污慩⁳䥗䡔⠠低佌䭃ഩऊ义䕎⁒佊义⌠琣浥潰慲祲摩楬瑳传⁎⑛牐浩牡䭹祥潊湩潃摮瑩潩嵮਍嬉匤畯捲呥扡敬潊湩嵳഻.
        /// </summary>
        internal static string RandomSubsetQuery {
            get {
                return ResourceManager.GetString("RandomSubsetQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⴠ匭瑥楴杮䤠敤瑮瑩⁹潃畬湭਍匠呅䤠䕄呎呉彙义䕓呒嬠䐤獥楴慮楴湯慔汢嵥嬠䤤敤瑮瑩䥹獮牥却慴整㭝਍.
        /// </summary>
        internal static string SetIdentityInsertQuery {
            get {
                return ResourceManager.GetString("SetIdentityInsertQuery", resourceCulture);
            }
        }
    }
}
